name: Build and Deploy Frontend to Azure

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
      - '.github/workflows/azure-frontend-build-deploy.yml'
  workflow_dispatch:

jobs:
  build-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APP_API_TOKEN }}
          action: "upload"
          app_location: "./frontend"
          api_location: ""
          output_location: "build"
