name: Build and Deploy Frontend to Azure

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'

jobs:
  build-deploy-frontend:
    runs-on: ubuntu-latest
    permissions:
       id-token: write
       contents: read


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Build frontend
        run: npm run build --if-present
        working-directory: ./frontend

      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_GRASS_0FF222603 }}
          action: "upload"
          app_location: "./frontend"
          api_location: ""
          output_location: "build"
