name: Deploy KeepAlive Function App

on:
  push:
    branches:
      - master
    paths:
      - 'KeepAliveFunctionApp/**'
      - '.github/workflows/deploy-keepalive.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore KeepAliveFunctionApp/KeepAliveFunctionApp.csproj

      - name: Build
        run: dotnet build KeepAliveFunctionApp/KeepAliveFunctionApp.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish KeepAliveFunctionApp/KeepAliveFunctionApp.csproj --configuration Release --output ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: false

      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: FamilyTaskManager-KeepAlive
          package: ./publish
