name: Keep Azure SQL Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:       # optional: allows manual run

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Database
        uses: azure/sql-action@v2
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: ./scripts/keepalive.sql